#!/bin/bash

if [[ -z ${RUN_DEV_ENV_TMP} ]]; then
    RUN_DEV_ENV_TMP=/opt/sbox/${USER}/tmp
fi
echo "Temp directory is ${RUN_DEV_ENV_TMP}"

if [[ ! -d ${RUN_DEV_ENV_TMP} ]]; then
    mkdir -p ${RUN_DEV_ENV_TMP}
    if [[ $? -ne 0 ]]; then
        echo "Failed to create temp directory ${RUN_DEV_ENV_TMP}"
        exit 1
    fi
fi

if [[ ! -d ${RUN_DEV_ENV_TMP}/distcc ]]; then
    mkdir -p ${RUN_DEV_ENV_TMP}/distcc
fi

CE65_RUN_DEV_ENV_REGISTRY=${CE65_RUN_DEV_ENV_REGISTRY:-"apps-jenkins:18888"}
CE65_RUN_DEV_ENV_REPO=${CE65_RUN_DEV_ENV_REPO:-"devserver-centos65"}
CE65_RUN_DEV_ENV_REPO_TAG=${CE65_RUN_DEV_ENV_REPO_TAG:-"latest"}

tmpfile=$(mktemp ${RUN_DEV_ENV_TMP}/launch-script.XXXXXX)
echo "#!/bin/bash" >> ${tmpfile}
if [[ -n ${CE65_ENVIRONMENT_FILE} ]]; then
	cat ${CE65_ENVIRONMENT_FILE} >> ${tmpfile}
else
	echo source /usr/local/devtools/bin/soldev_env.sh >> ${tmpfile}
fi
ARGS=""
whitespace="[[:space:]]"
for ARG in "$@"
do
    if [[ $# -eq 1 ]]; then
        ARGS="$@"
        break;
    fi
    # For other cases use bash -c
    if [[ $1 == "bash" ]] &&
       [[ $2 == "-c" ]]; then
        ARGS="$1 $2 \"${@:3}\""
        break;
    fi
    # Special Cases
    if [[ ${ARG:0:1} == "&" ]] ||
       [[ ${ARG} =~ " && " ]] ||
       [[ ${ARG} =~ " || " ]] ||
       [[ ${ARG:0:2} == "2>" ]] ||
       [[ ${ARG:0:2} == "1>" ]] ||
       [[ ${ARG:0:1} == ">" ]] ||
       [[ ${ARG:0:1} == "<" ]] ||
       [[ ${ARG:0:1} == "|" ]] ||
       [[ ${ARG:0:1} == ";" ]]
    then
       ARGS="$ARGS $ARG"
    else if [[ ${ARG} =~ "=" ]] && ! [[ ${ARG%=*} =~ $whitespace ]]
        then
            ARGS="$ARGS ${ARG%=*}=\"${ARG#*=}\""
        else
            # Escape any \
            ARG="${ARG//\\/\\\\}"
            ARGS="$ARGS \"${ARG//\"/\\\"}\""
        fi
    fi
done
echo ${ARGS} >> ${tmpfile}
chmod 777 ${tmpfile}

origfile=/tmp/$(basename ${tmpfile})

if [[ $# -ne 0 ]]; then
	COMMANDS=" -c '${origfile}'"
fi

VOLUMES="-v /opt/cvsdirs:/opt/cvsdirs -v /opt/sbox:/opt/sbox -v /usr/local/devtools:/usr/local/devtools -v /opt/soldev:/opt/soldev -v /opt/tools:/opt/tools -v /home:/home -v /etc/krb5.conf:/etc/krb5.conf -v /etc/krb5.keytab:/etc/krb5.keytab -v /etc/krb5.conf.d:/etc/krb5.conf.d -v /etc/nsswitch.conf:/etc/nsswitch.conf -v /opt/fc4-usr-local:/opt/fc4-usr-local -v /etc/sysconfig/authconfig:/etc/sysconfig/authconfig -v=/var/lib/sss/pipes/:/var/lib/sss/pipes/:rw -v ${RUN_DEV_ENV_TMP}:/tmp -v /dev:/dev"

PULL_COMMAND="docker pull  ${CE65_RUN_DEV_ENV_REGISTRY}/${CE65_RUN_DEV_ENV_REPO}:${CE65_RUN_DEV_ENV_REPO_TAG}"
if ! eval ${PULL_COMMAND}; then
    docker login -u solace -p solace1 ${CE65_RUN_DEV_ENV_REGISTRY} 2>/dev/null
    if ! eval ${PULL_COMMAND}; then
        echo "Failed to pull ${CE65_RUN_DEV_ENV_REGISTRY}/${CE65_RUN_DEV_ENV_REPO}:${CE65_RUN_DEV_ENV_REPO_TAG}"
        exit -1
    fi
fi

/usr/sbin/losetup --find
INTERACTIVE_OPT=
if [[ -t 1 ]]; then
    INTERACTIVE_OPT="-it" 
    COMMAND="/bin/bash --login ${COMMANDS}"
else
    COMMAND="/bin/bash ${COMMANDS}"
fi

docker run ${INTERACTIVE_OPT} --rm --privileged=true --net=host -u $(id -u):$(id -g) ${VOLUMES} \
        --env USER=${USER} --env HOME=${HOME} --env DISPLAY="${DISPLAY}" --workdir=${PWD} \
        ${CE65_EXTRA_DOCKER_OPTIONS} \
        ${CE65_RUN_DEV_ENV_REGISTRY}/${CE65_RUN_DEV_ENV_REPO}:${CE65_RUN_DEV_ENV_REPO_TAG} ${COMMAND}; ret=$?

rm "${tmpfile}"
/usr/sbin/losetup --detach-all

exit ${ret}
